export const lightTheme = {
    colors: {
        primary: '#007AFF',
        secondary: '#5856D6',
        success: '#34C759',
        danger: '#FF3B30',
        warning: '#FF9500',
        info: '#5AC8FA',

        background: '#F2F2F7',
        card: '#FFFFFF',
        text: '#000000',
        textSecondary: '#3C3C43',
        border: '#C6C6C8',
        gray: '#8E8E93',
        lightGray: '#E5E5EA',
        accent: '#FF2D55',
        disabled: '#C7C7CC',
        placeholder: '#C7C7CC',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
    },
    borderRadius: {
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
    },
    fontSize: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 24,
        xxl: 32,
    },
};
export const darkTheme = {
    colors: {
        primary: '#0A84FF',
        secondary: '#5E5CE6',
        success: '#32D74B',
        danger: '#FF453A',
        warning: '#FF9F0A',
        info: '#64D2FF',

        background: '#000000',
        card: '#1C1C1E',
        text: '#FFFFFF',
        textSecondary: '#EBEBF5',
        border: '#38383A',
        gray: '#8E8E93',
        lightGray: '#2C2C2E',
        accent: '#FF375F',
        disabled: '#48484A',
        placeholder: '#48484A',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
    },
    borderRadius: {
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
    },
    fontSize: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 24,
        xxl: 32,
    },
};
